include: package:supernova/lints.yaml
#include package: flutter/lints
linter:
  rules:
    prefer_double_quotes: true
    prefer_single_quotes: false
    require_trailing_commas: false

dart-code-metrics:
  rules-exclude:
    - prefer-trailing-comma
    - prefer-immediate-return
