name: bbs4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  encrypt: ^5.0.3
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_window_close: ^1.2.0
  gsheets: ^0.5.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  printing: ^5.12.0
  screenshot: ^3.0.0
  supernova:
    git:
      url: https://github.com/JonasWanke/supernova.git
      path: supernova
      ref: 4d3c562e44e824c537aa0ddfe3ce649dd4fa7e98

  uuid: 3.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/
