name: Flutter Build

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows

      - name: Build Release
        uses: softprops/action-gh-release@v2

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release Build"
          files: |
            *
