name: Flutter build

on:
  push:
     tags:
       - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows

      - name: Build Release
        uses: softprops/action-gh-release@v2
