name: Flutter build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows

      - uses: actions/checkout@master
      - name: Build Tag
        uses: laputansoft/github-tag-action@v4.6
        with:
          github_token: ${{ env.github-token }}
          tag: ${{ steps.package-version.outputs.version }}

      - name: Build Release
        uses: softprops/action-gh-release@v2
