name: Flutter Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows

      - name: Compress Build Folder
        run: |
          cp build\windows\x64\runner\Release\ .\bbs4
          tar -a -c -f bbs4.zip bbs4

      - name: Upload assets
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .\bbs4.zip
          asset_name: program-${{ runner.os }}.zip
          asset_content_type: application/zip
