name: Flutter Build

on: push

jobs:
  test: 
    runs-on: windows-latest
    steps:
      - name: Configure git long paths
        run: |
          git config --system core.longpaths true
    
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Integration testing
        run: "flutter test integration_test"
        
  build:
    needs: test
    runs-on: windows-latest
    steps:
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build
        run: flutter build windows

      - name: Compress
        run: |
          xcopy /S build\windows\x64\runner\Release\ .\bbs4\
          powershell Compress-Archive .\bbs4 bbs4.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          prerelease: false
          files: bbs4.zip
